-- Synthetic upgrade fixture. Public column types/defaults and FK definitions
-- match the S1 catalog audit and the 2026-09-13 S3 read-only metadata supplement.
-- Run after 20260913000000; install the existing access migrations afterwards.
create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$
  select (nullif(current_setting('request.jwt.claims', true), '')::jsonb->>'sub')::uuid;
$$;
grant usage on schema auth to authenticated;
create table public.books (
  id serial primary key, title varchar(255) not null, published_year integer not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.chapters (
  id serial primary key, book_id integer not null, title varchar(255) not null,
  sort_order integer generated by default as identity,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint fk_book foreign key(book_id) references public.books(id) on delete cascade
);
create table public.questions (
  id serial primary key, chapter_id integer not null,
  sort_order integer generated by default as identity, question text not null,
  additional_questions text, answer text, score integer, tag text, priority integer default 0,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint fk_chapter foreign key(chapter_id) references public.chapters(id) on delete cascade
);
create table public.tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references better_auth.users(id) on delete restrict,
  started_at timestamptz not null default now(), expires_at timestamptz not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  is_active boolean not null default true
);
alter table public.tickets enable row level security;
create policy "Allow read own tickets" on public.tickets for select to authenticated using(user_id = auth.uid());
create schema auth_source;
create table auth_source.tickets (
  id bigint generated by default as identity primary key, user_id uuid not null,
  started_at timestamptz not null default now(), expires_at timestamptz not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  is_active boolean not null default true,
  constraint fk_user foreign key(user_id) references auth.users(id) on delete cascade
);
alter table auth_source.tickets enable row level security;
create policy "Allow read own tickets" on auth_source.tickets for select to authenticated using(user_id = auth.uid());
revoke all on schema auth_source from public, anon, authenticated, service_role;
revoke all on auth_source.tickets from public, anon, authenticated, service_role;
