-- Run after fresh auth schema and session access functions, in the same deployment.
-- Required transaction settings: app.ticket_source_id, app.ticket_target_user_id,
-- app.kakao_app_id. No email matching or expired-ticket mapping occurs here.
begin;
set local search_path = pg_catalog;
set local lock_timeout = '5s';
lock table public.tickets in access exclusive mode;
do $$
declare target_id uuid := current_setting('app.ticket_target_user_id')::uuid;
begin
  if to_regclass('auth_source.tickets') is not null then
    raise exception 'TICKET_ARCHIVE_ALREADY_EXISTS';
  end if;
  if not exists(select 1 from public.tickets where id = current_setting('app.ticket_source_id')::bigint
    and is_active and started_at <= now() and expires_at >= now()) then
    raise exception 'SELECTED_TICKET_NOT_ACTIVE';
  end if;
  perform 1 from better_auth.kakao_identities where user_id = target_id
    and app_id = current_setting('app.kakao_app_id') and status = 'confirmed' for share;
  if not found then raise exception 'TARGET_KAKAO_NOT_CONFIRMED'; end if;
  if exists(select 1 from pg_constraint where contype = 'f' and confrelid = 'public.tickets'::regclass) then
    raise exception 'UNEXPECTED_TICKET_DEPENDENCY';
  end if;
  if not exists(select 1 from pg_constraint where contype='f'
    and conrelid='public.tickets'::regclass and confrelid='auth.users'::regclass
    and conkey=array[(select attnum from pg_attribute
      where attrelid='public.tickets'::regclass and attname='user_id')]::smallint[]) then
    raise exception 'UNEXPECTED_TICKET_OWNER_REFERENCE';
  end if;
  if exists(select 1 from pg_trigger where tgrelid='public.tickets'::regclass and not tgisinternal) then
    raise exception 'UNEXPECTED_TICKET_TRIGGER';
  end if;
end $$;
create schema if not exists auth_source;
revoke all on schema auth_source from public;
revoke all on schema auth_source from anon, authenticated;
alter table public.tickets set schema auth_source;
revoke all on auth_source.tickets from public, anon, authenticated;
do $$ begin
  if exists(select 1 from pg_roles where rolname='service_role') then
    revoke all on auth_source.tickets from service_role;
  end if;
end $$;
create table public.tickets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references better_auth.users(id) on delete restrict,
  started_at timestamptz not null default now(),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_active boolean not null default true
);
insert into public.tickets(id,user_id,started_at,expires_at,created_at,updated_at,is_active)
select id, current_setting('app.ticket_target_user_id')::uuid,
  started_at,expires_at,created_at,updated_at,is_active
from auth_source.tickets where id=current_setting('app.ticket_source_id')::bigint;
-- Preserve the source ID while keeping future generated IDs above all legacy IDs.
select setval(pg_get_serial_sequence('public.tickets','id'),
  greatest((select coalesce(max(id),0) from auth_source.tickets)+1,1),false);
alter table public.tickets enable row level security;
revoke all on public.tickets from public, anon, authenticated;
grant select on public.tickets to authenticated;
create policy "Allow read own tickets" on public.tickets for select to authenticated
  using(user_id=auth.uid());
create policy "Require Better Auth session" on public.tickets as restrictive
  for select to authenticated using((select public.has_valid_auth_session(false)));
-- Recreate the SQL body against the newly created service table.
create or replace function public.has_active_ticket()
returns boolean language sql stable security invoker set search_path=pg_catalog as $$
  select public.has_valid_auth_session(true) and exists (
    select 1 from public.tickets where user_id=auth.uid()
      and is_active and started_at<=now() and expires_at>=now()
  );
$$;
revoke all on function public.has_active_ticket() from public, anon;
grant execute on function public.has_active_ticket() to authenticated;
commit;
